### ISSUE TITLE
A typo?

### ISSUE THREAD

**Issue by inkydragon** [hellerve/microml#2]
Maybe line 6 should be correct to `type = None`
https://github.com/hellerve/microml/blob/edd00ec77503c90f77f50a02ec0a2e22104a599f/microml/ast.py#L5-L6

for `ast.Id` dosn't have a property `type`. (Note that `class Id(Node) <: Node`)
 https://github.com/hellerve/microml/blob/edd00ec77503c90f77f50a02ec0a2e22104a599f/microml/typing.py#L96-L98

----

Also，we may add `argtypes` to `class Lambda(Node)`

https://github.com/hellerve/microml/blob/edd00ec77503c90f77f50a02ec0a2e22104a599f/microml/ast.py#L129-L134

https://github.com/hellerve/microml/blob/edd00ec77503c90f77f50a02ec0a2e22104a599f/microml/typing.py#L101-L106

**Comment by hellerve** [comment]
As for your first suggestion, good eye! I actually think we should correct `type` to `typ`, though, because `type` is already bound by Python and I’d prefer not to override it!

As for your second suggestion, `argtypes`, confusingly, is set a little below as a property:

https://github.com/hellerve/microml/blob/edd00ec77503c90f77f50a02ec0a2e22104a599f/microml/ast.py#L129-L138

(Look at the last line!)

Maybe it should be an empty list, though. This is all pretty hacky as of yet, so I welcome any style input!

**Comment by hellerve** [comment]
Should we close this now that #3 is merged or do you want to do something about the second item on the issue’s agenda as well?

**Comment by inkydragon** [comment]
I'm tring to understand what `typing.py` does. It may takes some time. 
If I've got a good idea, I would like to open a new pr directly.

So, I'll close this issue.

**Comment by hellerve** [comment]
I have the link in the README so maybe you’ve seen it before, but [Eli Bendersky has a blog post](https://eli.thegreenplace.net/2018/type-inference/) where he explains the type inference. I merely added the compiler and interpreter and changed the code where appropriate.
